name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Or Java 11, depending on your JMeter version

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.6.3
          echo "$JMETER_HOME/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          mkdir -p jmeter/report  # <== Add this line
          apache-jmeter-5.6.3/bin/jmeter -n -t jmeter/test-plan.jmx -l result.jtl -e -o jmeter/report

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: jmeter/report
